server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: ${GET_URI_CONFIG}
          default-label: "main"
          skip-ssl-validation: true
          username: "BGNC"
          password: ${GIT_KEY}


