server:
  port: 9099

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1322
    url: jdbc:postgresql://localhost:5432/AuthDB
  jpa:
    hibernate:
      ddl-auto: update
